name: publish 
on: [push]
jobs:
 myjob:     
  runs-on: ubuntu-latest
  - steps:
   - uses: actions/checkout@v2
   - name: Login to GitHub Container Registry
   uses: docker/login-action@v1
   with:
    registry: ghcr.io
    username: ${{ github.actor }}
    password: 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
   - name: Build the hello-docker Docker image
    run:  
              docker build . --tag ghcr.io/Napoleon280/dockerfiles:latest
              docker run ghcr.io/Napoleon280/dockerfiles:latest
              docker push ghcr.io/Napoleon280/dockerfiles:latest
