name: publish 

on: [push]

jobs:
  myjob:     
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: Napoleon280  
          password: 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
      - name: Build the hello-docker Docker image
        run:  
          docker build . --tag ghcr.io/Napoleon280/dockerfiles:latest
          docker run ghcr.io/Napoleon280/dockerfiles:latest
          docker push ghcr.io/Napoleon280/dockerfiles:latest